### ISSUE TITLE
How to dynamically enable/disable authentication?

### ISSUE THREAD

**Issue by tchap** [abbot/go-http-auth#2]
The situation is following:
- `config.yaml` is structured in the following way:

```
auth:
  - /path1:
      - username1: <username>
        password1: <password>
      - username2: <username>
        password2: <password>
  - /path2:
      - username: <username>
        password: <password>
```

Now during the app initialization, I would like to enable Basic authentication for the path if respective path record is present and disable it otherwise (i.e. let all incoming request pass). I didn't manage to do that in any way, because auth expects `auth.AuthenticatedHandlerFunc` while http expects `http.HandlerFunc` and they are not interchangeable. That means that you need 2 handler functions - one for normal http, the other for Basic auth. That is kinda cumbersome.

So I just wanted to ask if I didn't oversee something. Am I right that it cannot be done easily as the interface is design right now?

Perhaps there could be another version of `auth.Wrap` that would simply put an empty Username into the `AuthenticatedRequest` passed into the handler and would not even attempt to authenticate the request?

Let me know what you think about it, I could even write it myself and send a pull request!
